### ISSUE TITLE
 check  out  the    acc,    and  Score

### ISSUE THREAD

**Issue by chumingqian** [microsoft/RespireNet#3]
Hello,  author: 
     I   think  you    let   acc   =  Score,   in  your    valid  stage  code,  you  let :    

      `acc = accuracy_score(y_true, y_pred)`

   however,  the  official   scocre   defination  :   score  =   (sp + se)/2  which    you  use  it  in the  training  stage  but  in the  valid stage you  use    acc  instead.

   Can   you  check  it  out,  thanks   a lot.

**Comment by sidgairo18** [comment]
Thanks for your comment. The `get_score` function is used to compute the official score, see https://github.com/microsoft/RespireNet/blob/5e3f41aaec93e87eba9e06a67fe93c56b391b5a8/train.py#L189

Feel free to uncomment it when you evaluate your models :)
